### ISSUE TITLE
No --device=/dev/dri, glxgears is not running on nvidia gpu

### ISSUE THREAD

**Issue by LiangHuangBC** [ehfd/docker-nvidia-egl-desktop#8]
My host machine is ubuntu18.04 with 4 nvidia gpus.  And I don't have /dev/dri node, with nvidia driver, I have /dev/nvidia0, /dev/nvidia1, /dev/nvidia2, /dev/nvidia3 instead. I can docker run, and connect vnc, but can not use gpu.
![image](https://user-images.githubusercontent.com/40865875/109212994-7d831e00-7786-11eb-9ffb-7b8f12a585a1.png)
![image](https://user-images.githubusercontent.com/40865875/109213726-54af5880-7787-11eb-9b43-f2c8761c861f.png)

I can run glxgears, or vglrun glxgears, but not on gpu. 
Command to start container is :    
docker run --gpus 1 -it -e SIZEW=1920 -e SIZEH=1080 -e CDEPTH=24 -e SHARED=TRUE -e VNCPASS=vncpasswd -p 5901:5901 -v "/tmp/.docker.xauth:/tmp/.docker.xauth"  -e XAUTHORITY=/tmp/.docker.xauth --name vv --rm  --runtime=nvidia ehfd/nvidia-egl-desktop:latest

**Comment by ehfd** [comment]
Yeah. llvmpipe means you are not using the GPU. You need the /dev/dri DRM devices and it is supposed to be available if your Kernel Modesetting is set up correctly during NVIDIA driver install.
Probably blacklist the Nouveau open source driver or install the NVIDIA driver with your OS's own package manager. Not a container issue. Will keep it open for more questions.

**Comment by LiangHuangBC** [comment]
Thanks for quick reply. Your another image ehfd/docker-nvidia-glx-desktop is working well, so we are on it now.  Thanks for your work.

**Comment by ehfd** [comment]
https://github.com/mviereck/x11docker/wiki/Hardware-acceleration#share-nvidia-device-files-with-container

Check if these are inside the containers. This repo has less issues. https://github.com/ehfd/docker-nvidia-glx-desktop will be rebuilt when NVIDIA enables XWayland support in 470.xx drivers.

**Comment by ehfd** [comment]
@LiangHuangBC 

This container is guaranteed to work on multiple desktops over ehfd/docker-nvidia-glx-desktop (which uses quite hacky configurations to use Xorg inside containers) and is the recommended container to use. But since this container doesn't support Vulkan, if you need Vulkan use https://github.com/mviereck/x11docker over ehfd/docker-nvidia-glx-desktop, but you need to use docker on one single node with full root control and cannot be used on other container orchestration platforms.

Anyways, to troubleshoot this problem:

You likely did not disable Nouveau properly or your NVIDIA drivers are incorrect. Reinstall NVIDIA drivers or if you don't know how, install the whole OS again, preferably with `sudo ubuntu-drivers autoinstall` to install recommended drivers or `sudo apt-get install nvidia-driver-460` ([this package](https://packages.ubuntu.com/focal/nvidia-driver-460) for example if you want to specify a specific version in Ubuntu.

For RHEL and CentOS [check this link](https://www.advancedclustering.com/act_kb/installing-nvidia-drivers-rhel-centos-7/).

But on any distribution, select **yes** especially when you see something similar to this:

`Would you like to register the kernel module sources with DKMS? This will allow DKMS to automatically build a new module, if you install a different kernel later.`

You should have the DRM devices available after reboot if you selected yes.

**Comment by LiangHuangBC** [comment]
Thanks a lot for your help, I tried your glx image, which is good but only one people can use it. The thing is after run that glx image, /dev/dri appears on host machine (side effect of --privileged?? ), now we can use this egl image. Now we are running gazebo and ros on it, lucky~~.  Another thing is now I need vulkan for lgsvl simulator, then we ordered new machines for it. Hopefully Nvidia will release new driver soon, we can go back to containers' world.

**Comment by LeehanLee** [comment]
> Thanks a lot for your help, I tried your glx image, which is good but only one people can use it. The thing is after run that glx image, /dev/dri appears on host machine (side effect of --privileged?? ), now we can use this egl image. Now we are running gazebo and ros on it, lucky~~. Another thing is now I need vulkan for lgsvl simulator, then we ordered new machines for it. Hopefully Nvidia will release new driver soon, we can go back to containers' world.

hi @LiangHuangBC , you mentioned you have ran gazebo on this **docker-nvidia-egl-desktop** container, did you see the render area of gazebo keeps flickering?

**Comment by ehfd** [comment]
`/dev/dri` is no longer required for NVIDIA GPUs. Use `VGL_DISPLAY=egl[n]` or default.
